#!/bin/sh
# Builds TypeThru.app in the project root.
set -e
cd "$(dirname "$0")/.."
for tool in git clang++ swiftc codesign; do
    command -v "$tool" >/dev/null 2>&1 || {
        echo "Missing $tool. Install the Xcode Command Line Tools with: xcode-select --install"
        exit 1
    }
done
# DECISION: make check builds a throwaway copy elsewhere, which must not reset Accessibility.
APP=${TYPETHRU_APP:-TypeThru.app}

# A stable signing identity lets macOS keep the Accessibility permission across builds.
# Any code signing certificate works: paid Developer ID, free Apple Development, or self-signed.
# Set TYPETHRU_SIGN_IDENTITY to a certificate name or hash, or to - to force ad-hoc signing.
# DECISION: without the variable, prefer Developer ID, then Apple Development, then ad-hoc.
IDENTITY=${TYPETHRU_SIGN_IDENTITY-}
if [ -z "$IDENTITY" ]; then
    IDENTITIES=$(security find-identity -v -p codesigning 2>/dev/null || true)
    for kind in 'Developer ID Application' 'Apple Development'; do
        IDENTITY=$(printf '%s\n' "$IDENTITIES" | awk -v k="\"$kind:" 'index($0, k) { print $2; exit }')
        [ -n "$IDENTITY" ] && break
    done
fi
IDENTITY=${IDENTITY:--}
NAME=
if [ "$IDENTITY" = - ]; then
    echo 'Signing: ad-hoc (macOS will ask for Accessibility again after each build)'
else
    NAME=$(security find-identity -p codesigning 2>/dev/null | awk -v h="$IDENTITY" '$2 == h { sub(/^[^"]*/, ""); print; exit }')
    echo "Signing: ${NAME:-$IDENTITY}"
fi
# DECISION: --timestamp=none keeps local builds offline. Notarization (package.sh) needs a
# Developer ID with a secure timestamp and the hardened runtime.
case "$NAME" in
    *'Developer ID Application:'*) sign() { codesign --force --timestamp --options runtime --sign "$IDENTITY" "$@"; } ;;
    *) sign() { codesign --force --timestamp=none --sign "$IDENTITY" "$@"; } ;;
esac

REV=072fa83e824c1b633f508f60cbad87b41aab3047
SOURCE=.build/virtualhid-source
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources" .build/module-cache
if [ ! -d "$SOURCE/.git" ]; then
    git init "$SOURCE"
    git -C "$SOURCE" remote add origin https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice.git
    git -C "$SOURCE" fetch --depth 1 origin "$REV"
    git -C "$SOURCE" checkout --detach FETCH_HEAD
fi
[ "$(git -C "$SOURCE" rev-parse HEAD)" = "$REV" ] || { echo 'Unexpected virtual HID source revision'; exit 1; }
# DECISION: universal binaries, so one download runs on Apple silicon and Intel Macs.
clang++ -std=c++23 -O2 -Wall -Wextra -pthread -arch arm64 -arch x86_64 -mmacosx-version-min=13.0 -I "$SOURCE/include" -I "$SOURCE/vendor/vendor/include" \
    helper/virtual-keyboard.cpp -o "$APP/Contents/Resources/TypeThru-VirtualKeyboard"
sign --identifier io.github.sayre4ux.typethru.virtual-keyboard "$APP/Contents/Resources/TypeThru-VirtualKeyboard"
"$APP/Contents/Resources/TypeThru-VirtualKeyboard" --check-protocol
rm -f "$APP/Contents/Resources/"*.command "$APP/Contents/Resources/"*.sh "$APP/Contents/Resources/KeyTyper-VirtualKeyboard"
cp helper/install-helper.sh helper/uninstall-helper.sh "$APP/Contents/Resources/"
cp "$SOURCE/dist/Karabiner-DriverKit-VirtualHIDDevice-8.6.0.pkg" "$APP/Contents/Resources/"
cp "$SOURCE/LICENSE.md" "$APP/Contents/Resources/Karabiner-LICENSE.txt"
cp Resources/AppIcon.icns "$APP/Contents/Resources/"
# Fingerprints of the files setup runs as root. The app checks root-owned copies against them,
# because the installed bundle is writable by the user (see VirtualKeyboard.adminCommand).
{
    echo '// Generated by build.sh. Do not edit.'
    echo 'enum ResourceHashes {'
    echo '    static let sha256: [String: String] = ['
    for file in install-helper.sh uninstall-helper.sh TypeThru-VirtualKeyboard Karabiner-DriverKit-VirtualHIDDevice-8.6.0.pkg; do
        echo "        \"$file\": \"$(shasum -a 256 "$APP/Contents/Resources/$file" | cut -c1-64)\","
    done
    echo '    ]'
    echo '}'
} > .build/ResourceHashes.swift
for arch in arm64 x86_64; do
    swiftc -O -target "$arch-apple-macos13.0" -module-cache-path "$PWD/.build/module-cache" \
        Sources/*.swift .build/ResourceHashes.swift -o ".build/TypeThru-$arch"
done
lipo -create .build/TypeThru-arm64 .build/TypeThru-x86_64 -output "$APP/Contents/MacOS/TypeThru"
cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleIdentifier</key><string>io.github.sayre4ux.typethru</string>
  <key>CFBundleName</key><string>TypeThru</string>
  <key>CFBundleExecutable</key><string>TypeThru</string>
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>0.3</string>
  <key>CFBundleVersion</key><string>3</string>
  <key>LSMinimumSystemVersion</key><string>13.0</string>
  <key>LSUIElement</key><true/>
</dict>
</plist>
PLIST
sign --identifier io.github.sayre4ux.typethru "$APP"

# macOS ties the Accessibility permission to the signature. When the new build cannot reuse the
# old permission (ad-hoc, or a different identity), clear the stale entry so macOS asks cleanly.
echo "Built $(pwd)/$APP"
[ "$APP" = TypeThru.app ] || exit 0
LAST=$(cat .build/last-sign-identity 2>/dev/null || true)
if [ "$IDENTITY" = - ] || [ "$IDENTITY" != "$LAST" ]; then
    tccutil reset Accessibility io.github.sayre4ux.typethru >/dev/null 2>&1 || true
    echo 'Cleared the old Accessibility permission. Allow TypeThru again when it asks.'
fi
printf '%s\n' "$IDENTITY" > .build/last-sign-identity
pgrep -x TypeThru >/dev/null && echo 'TypeThru is still running the previous build. Quit and reopen it.' || true
